name = "newsapp"
compatibility_date = "2024-08-11"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "newsweblist"
database_id = "cfa13d5e-3540-4c20-99ee-9f36d7562ec9"

# [ai]
# binding = "AI"